import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        title: "Sudadera 'Gravity' - Edición Limitada",
        description: "Sudadera de alta calidad con el logo de Antigravity bordado. Perfecta para cualquier ocasión, fabricada con algodón orgánico de 400g.",
        active: true,
        averageRating: 4.8,
        slug: "sudadera-gravity-edicion-limitada",
        category: { id: "cat1", name: "Ropa", slug: "ropa" },
        variants: [
            {
                id: "v1",
                name: "Negro / L",
                price: 45.99,
                stock: 50,
                images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "2",
        title: "Mochila Tech Pro",
        description: "La mochila definitiva para el profesional tecnológico. Compartimento para laptop de 16'', resistente al agua y carga USB integrada.",
        active: true,
        averageRating: 4.9,
        slug: "mochila-tech-pro",
        category: { id: "cat2", name: "Accesorios", slug: "accesorios" },
        variants: [
            {
                id: "v2",
                name: "Gris Espacial",
                price: 89.00,
                stock: 25,
                images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "3",
        title: "Auriculares Noise-Cancelling G1",
        description: "Sumérgete en el sonido sin distracciones. Hasta 40 horas de batería y cancelación activa de ruido de última generación.",
        active: true,
        averageRating: 4.7,
        slug: "auriculares-noise-cancelling-g1",
        category: { id: "cat3", name: "Electrónica", slug: "electronica" },
        variants: [
            {
                id: "v3",
                name: "Plata",
                price: 199.99,
                stock: 15,
                images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "4",
        title: "Teclado Mecánico RGB 'Nova'",
        description: "Interruptores mecánicos táctiles, iluminación RGB personalizable y diseño ergonómico para largas sesiones de trabajo o juego.",
        active: true,
        averageRating: 4.6,
        slug: "teclado-mecanico-rgb-nova",
        category: { id: "cat3", name: "Electrónica", slug: "electronica" },
        variants: [
            {
                id: "v4",
                name: "Layout ES",
                price: 120.00,
                stock: 10,
                images: ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "5",
        title: "Botella Térmica 'Flow'",
        description: "Mantiene tus bebidas frías por 24 horas o calientes por 12. Diseño minimalista en acero inoxidable de grado alimenticio.",
        active: true,
        averageRating: 4.5,
        slug: "botella-termica-flow",
        category: { id: "cat2", name: "Accesorios", slug: "accesorios" },
        variants: [
            {
                id: "v5",
                name: "Azul Mate",
                price: 24.50,
                stock: 100,
                images: ["https://images.unsplash.com/photo-1602143307185-8c150fa95a74?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "6",
        title: "Set de Escritorio 'Zen'",
        description: "Alfombrilla de cuero sintético, soporte para monitor de madera y organizador de cables. El set perfecto para tu setup minimalista.",
        active: true,
        averageRating: 5.0,
        slug: "set-escritorio-zen",
        category: { id: "cat2", name: "Accesorios", slug: "accesorios" },
        variants: [
            {
                id: "v6",
                name: "Madera de Nogal",
                price: 75.00,
                stock: 20,
                images: ["https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "7",
        title: "Lámpara de Escritorio Inteligente",
        description: "Control de temperatura de color, brillo ajustable y carga inalámbrica para móviles integrados en la base.",
        active: true,
        averageRating: 4.8,
        slug: "lampara-escritorio-inteligente",
        category: { id: "cat3", name: "Electrónica", slug: "electronica" },
        variants: [
            {
                id: "v7",
                name: "Blanco Glaciar",
                price: 59.99,
                stock: 30,
                images: ["https://images.unsplash.com/photo-1534073828943-f801091bb18c?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "8",
        title: "Ratón Ergonómico 'Volt'",
        description: "Diseño vertical para reducir la tensión de la muñeca. Sensor óptico de alta precisión y conectividad dual (Bluetooth/2.4G).",
        active: true,
        averageRating: 4.4,
        slug: "raton-ergonomico-volt",
        category: { id: "cat3", name: "Electrónica", slug: "electronica" },
        variants: [
            {
                id: "v8",
                name: "Negro Mate",
                price: 49.00,
                stock: 45,
                images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "9",
        title: "Camiseta Tech-Knit",
        description: "Tejido transpirable de alta tecnología que se adapta a tu cuerpo. Ideal para el día a día o entrenamiento intenso.",
        active: true,
        averageRating: 4.7,
        slug: "camiseta-tech-knit",
        category: { id: "cat1", name: "Ropa", slug: "ropa" },
        variants: [
            {
                id: "v9",
                name: "Gris / M",
                price: 29.99,
                stock: 60,
                images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "10",
        title: "Gorra 'Eclipse'",
        description: "Diseño estructurado con bordado 3D de alta densidad. Cierre ajustable metálico y visera pre-curvada.",
        active: true,
        averageRating: 4.5,
        slug: "gorra-eclipse",
        category: { id: "cat1", name: "Ropa", slug: "ropa" },
        variants: [
            {
                id: "v10",
                name: "Negro",
                price: 19.99,
                stock: 80,
                images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "11",
        title: "Soporte para Portátil 'Air'",
        description: "Aluminio aeronáutico, plegable y ultra-ligero. Mejora la postura y la ventilación de tu equipo.",
        active: true,
        averageRating: 4.9,
        slug: "soporte-portatil-air",
        category: { id: "cat2", name: "Accesorios", slug: "accesorios" },
        variants: [
            {
                id: "v11",
                name: "Plata Espacial",
                price: 35.00,
                stock: 40,
                images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
    {
        id: "12",
        title: "Altavoz Bluetooth 'Core'",
        description: "Resistente al agua (IPX7), sonido 360 grados y hasta 20 horas de reproducción. El alma de cualquier fiesta.",
        active: true,
        averageRating: 4.6,
        slug: "altavoz-bluetooth-core",
        category: { id: "cat3", name: "Electrónica", slug: "electronica" },
        variants: [
            {
                id: "v12",
                name: "Verde Bosque",
                price: 65.00,
                stock: 25,
                images: ["https://images.unsplash.com/photo-1608351489264-87462ddff74d?q=80&w=600&auto=format&fit=crop"],
            },
        ],
    },
];